#!/usr/bin/env zsh

successfully() {
  $* || (echo "\nfailed" 1>&2 && exit 1)
}

fancy_echo() {
  echo "\n$1"
}

# Development stack
if -f /etc/zshenv; then
  fancy_echo "Fixing OSX zsh environment bug ..."
    successfully sudo mv /etc/{zshenv,zshrc}
fi

fancy_echo "Installing Homebrew, a good OS X package manager ..."
  successfully ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  successfully brew update

fancy_echo "Installing the last git version ..."
  successfully brew install git

fancy_echo "Installing Redis, a good key-value database ..."
  successfully brew install redis

fancy_echo "Installing The Silver Searcher (better than ack or grep) to search the contents of files ..."
  successfully brew install the_silver_searcher

fancy_echo "Installing tree to recursively list directories ..."
  successfully brew install tree

fancy_echo "Installing boot2docker ..."
  successfully brew install boot2docker

fancy_echo "Installing ctags, to index files for vim tab completion of methods, classes, variables ..."
  successfully brew install ctags

fancy_echo "Installing ImageMagick, to crop and resize images ..."
  successfully brew install imagemagick

fancy_echo "Installing rbenv, to change Ruby versions ..."
  successfully brew install rbenv

  if ! grep -qs "rbenv init" ~/.zshrc; then
    successfully echo 'eval "$(rbenv init -)"' >> ~/.zshrc

    fancy_echo "Enable shims and autocompletion ..."
      successfully eval "$(rbenv init -)"
  fi

  source ~/.zshrc

fancy_echo "Installing rbenv-gem-rehash so the shell automatically picks up binaries after installing gems with binaries..."
  successfully brew install rbenv-gem-rehash

fancy_echo "Installing ruby-build, to install Rubies ..."
  successfully brew install ruby-build

fancy_echo "Installing Ruby 2.2.2 ..."
  successfully rbenv install 2.2.2

fancy_echo "Setting Ruby 2.2.2 as global default Ruby ..."
  successfully rbenv global 2.2.2
  successfully rbenv shell 2.2.2

fancy_echo "Installing Golang..."
  successfully brew install go

fancy_echo "Installing Elixir..."
  successfully brew install elixir

fancy_echo "Updating to latest Rubygems version ..."
  successfully gem update --system

fancy_echo "Installing critical Ruby gems for Rails development ..."
  successfully gem install bundler pg rails --no-document

fancy_echo "Configuring Bundler for faster, parallel gem installation ..."
  number_of_cores=`sysctl -n hw.ncpu`
  bundle config --global jobs `expr $number_of_cores - 1`

fancy_echo "Installing GitHub CLI client ..."
  successfully brew install hub

fancy_echo "Installing Heroku CLI client ..."
  successfully brew install heroku-toolbelt

fancy_echo "Installing MacVim ..."
  successfully brew install macvim

fancy_echo "Installing Wget..."
  successfully brew install wget

# Applications not on Apple Store
fancy_echo "Installing brew-cask to install Mac applications distributed as binaries..."
  successfully brew tap phinze/homebrew-cask
  successfully brew install brew-cask

# Change Homebrew cask installation dir
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

fancy_echo "Installing Spectacle app ..."
  successfully brew cask install spectacle

fancy_echo "Installing Transmission app ..."
  successfully brew cask install transmission

fancy_echo "Installing Iterm2 app ..."
  successfully brew cask install iterm2

fancy_echo "Installing Postgres app ..."
  successfully brew cask install postgres

fancy_echo "Installing Spotify app ..."
  successfully brew cask install spotify

fancy_echo "Installing VLC app ..."
  successfully brew cask install vlc

fancy_echo "Installing Libre Office app ..."
  successfully brew cask install libre-office

fancy_echo "Installing MacDown app ..."
  successfully brew cask install macdown

fancy_echo "Installing AppCleaner app ..."
  successfully brew cask install appcleaner

fancy_echo "Installing Alfred2 app ..."
  successfully brew cask install alfred

if ! grep -qs "DO NOT EDIT BELOW THIS LINE" ~/.zshrc; then
  fancy_echo "Prepare ~/.zshrc for http://github.com/sush/dotfiles ..."
    successfully echo "# DO NOT EDIT BELOW THIS LINE\n" >> ~/.zshrc
fi
